name: flutter_tasks
description: A rough clone of the Google Tasks app with Flutter.
publish_to: "none"

version: 1.0.0+1

environment:
    sdk: ">=2.7.0 <3.0.0"

dependencies:
    flutter:
        sdk: flutter
    path: ^1.7.0
    sqflite: ^1.3.0
    uuid: ^3.0.1        

dev_dependencies:
    flutter_test:
        sdk: flutter

    lint: ^1.5.2

flutter:
    uses-material-design: true

    assets:
        - assets/

    fonts:
        - family: Product Sans
          fonts:
              - asset: fonts/ProductSans-Regular.ttf
              - asset: fonts/ProductSans-Medium.ttf
                weight: 500
              - asset: fonts/ProductSans-Bold.ttf
                weight: 700
